#Name of the workflow
name: CI/CD

on:
   workflow_dispatch:
    inputs:
        env: 
          default: 'dev'
          description: This is the environment where the workflow run
          required: true
          type: choice
          options:
            - dev
            - prod
            - staging
            - UAT
            
jobs:
  pull:
      runs-on: ubuntu-latest
      steps:
        - name: "checkout the code"
          run: echo "code checkout"
  build:
      runs-on: ubuntu-latest
      needs: pull
      steps:
        - name: "build the code"
          run: echo "code build"
          
  Test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: "test the code"
          run: echo "code tested"
  deploy:
      runs-on: ubuntu-latest
      needs: Test
      steps:
        - name: "deploy the code"
          run: echo "code is deployed"
          
