#This is the workflow name
name: Hello
on: 
 workflow_dispatch: 

#These are the job inside the workflow
jobs:
    greet:
      runs-on: ubuntu-latest
      steps:
        - name: "say hello to user"
          run: echo "hey hello Amit"

        - name: "say hello to ubuntu user"
          run: echo "Hello $USER"

    detail: 
       runs-on: ubuntu-latest
       steps:
         - name: "show the version of docker & python"
           run: docker --version && python --version
          
          
