name: python-lintel

on:
  push:
    branches: [main]

jobs:

    lintel-check:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: False
          matrix: 
            python-versions: ["3.9", "3.10", "3.11", "3.12", "3.13"]


        steps:
            - name: code-checout
              uses: actions/checkout@v4


            - name: python steup
              uses: actions/setup-python@v5
              with:
                python-version: ${{matrix.python-versions}}

                
            - name: install dependencies
              run: pip install -r requirement.txt

            - name: run linter
              run: flake8 app.py
