#API keys, sensitive data, credentials
#Gitleaks

name: Secret scan
on:
    workflow_call:
jobs:

    secret-scanning:
        runs-on:
            ubuntu-latest
        steps:
            - name: check out the code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: run git leaks scanner
              uses: gitleaks/gitleaks-action@v2
              env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
        
